In [3]:
import numpy as np

In [4]:
x = (1,2,3,4)

In [5]:
type(x)

tuple

In [6]:
arr = np.array(x)

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((1,4))

array([[1., 1., 1., 1.]])

In [38]:
arr1=np.random.randint(1,100,20)

In [49]:
arr1

array([12, 33, 10, 19, 79, 13, 37, 61, 39, 60, 22, 43, 52, 16, 28, 56, 93,
       46, 83, 48], dtype=int32)

In [126]:
np.random.seed(50)
arr2=np.random.randint(0,1000,21).reshape(7,3)
arr2

array([[688, 480, 907],
       [109, 289, 990],
       [132,  70, 229],
       [ 70, 278, 749],
       [133, 258,  95],
       [250,  71, 367],
       [452, 974, 163]], dtype=int32)

In [127]:
arr2.max()

np.int32(990)

In [129]:
arr2.min()

np.int32(70)

In [132]:
arr2.mean()

np.float64(369.23809523809524)

In [135]:
arr2.argmin()

np.int64(7)

In [137]:
arr2.argmax()

np.int64(5)

In [139]:
arr2.shape

(7, 3)

In [146]:
row=0
column=0

In [148]:
arr2[row, column]

np.int32(688)

In [153]:
row=3
column=2
arr2[row, column]

np.int32(749)